/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/2IHEL96JR5L
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Arimo } from 'next/font/google'

arimo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
'use client';

import Link from "next/link"
import { DropdownMenu, DropdownMenuTrigger, DropdownMenuContent, DropdownMenuLabel, DropdownMenuSeparator, DropdownMenuItem } from "@/components/ui/dropdown-menu"
import { Button } from "@/components/ui/button"
import { Card, CardHeader, CardTitle, CardDescription, CardContent } from "@/components/ui/card"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import { Table, TableHeader, TableRow, TableHead, TableBody, TableCell } from "@/components/ui/table"
import { Badge } from "@/components/ui/badge"
import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar"

export function lookbackDashboard_3() {
  return (
    <div className="flex flex-col w-full min-h-screen bg-background">
      <header className="sticky top-0 z-40 flex h-16 w-full items-center justify-between border-b bg-background px-4 sm:px-6">
        <Link href="#" className="flex items-center gap-2" prefetch={false}>
          <MountainIcon className="h-6 w-6" />
          <span className="text-lg font-semibold">Acme Inc</span>
        </Link>
        <nav className="flex items-center gap-4">
          <Link href="#" className="text-muted-foreground hover:text-foreground" prefetch={false}>
            Dashboard
          </Link>
          <Link href="#" className="text-primary font-medium" prefetch={false}>
            Feedback
          </Link>
          <Link href="#" className="text-muted-foreground hover:text-foreground" prefetch={false}>
            Updates
          </Link>
          <DropdownMenu>
            <DropdownMenuTrigger asChild>
              <Button variant="ghost" size="icon" className="rounded-full">
                <img
                  src="/placeholder.svg"
                  width={36}
                  height={36}
                  alt="Avatar"
                  className="rounded-full"
                  style={{ aspectRatio: "36/36", objectFit: "cover" }}
                />
              </Button>
            </DropdownMenuTrigger>
            <DropdownMenuContent align="end">
              <DropdownMenuLabel>My Account</DropdownMenuLabel>
              <DropdownMenuSeparator />
              <DropdownMenuItem>Settings</DropdownMenuItem>
              <DropdownMenuItem>Logout</DropdownMenuItem>
            </DropdownMenuContent>
          </DropdownMenu>
        </nav>
      </header>
      <main className="flex-1">
        <section className="py-8 sm:py-12">
          <div className="container grid gap-8">
            <div>
              <h1 className="text-3xl font-bold">Feedback</h1>
              <p className="text-muted-foreground">Share your thoughts and help us improve our service.</p>
            </div>
            <div className="grid gap-6 md:grid-cols-2 lg:grid-cols-3">
              <Card>
                <CardHeader>
                  <CardTitle>Submit Feedback</CardTitle>
                  <CardDescription>Let us know how we can improve your experience.</CardDescription>
                </CardHeader>
                <CardContent>
                  <form className="grid gap-4">
                    <div className="grid gap-2">
                      <Label htmlFor="subject">Subject</Label>
                      <Input id="subject" placeholder="Enter a subject" />
                    </div>
                    <div className="grid gap-2">
                      <Label htmlFor="message">Message</Label>
                      <Textarea id="message" placeholder="Share your feedback..." rows={4} />
                    </div>
                    <Button type="submit">Submit Feedback</Button>
                  </form>
                </CardContent>
              </Card>
              <Card>
                <CardHeader>
                  <CardTitle>Feedback History</CardTitle>
                  <CardDescription>View and track the status of your past feedback.</CardDescription>
                </CardHeader>
                <CardContent>
                  <Table>
                    <TableHeader>
                      <TableRow>
                        <TableHead>Subject</TableHead>
                        <TableHead>Status</TableHead>
                        <TableHead>Date</TableHead>
                      </TableRow>
                    </TableHeader>
                    <TableBody>
                      <TableRow>
                        <TableCell>Improve search functionality</TableCell>
                        <TableCell>
                          <Badge variant="secondary">In Progress</Badge>
                        </TableCell>
                        <TableCell>2023-05-12</TableCell>
                      </TableRow>
                      <TableRow>
                        <TableCell>Add more payment options</TableCell>
                        <TableCell>
                          <Badge variant="outline">Pending</Badge>
                        </TableCell>
                        <TableCell>2023-04-28</TableCell>
                      </TableRow>
                      <TableRow>
                        <TableCell>Enhance mobile experience</TableCell>
                        <TableCell>
                          <Badge variant="secondary">In Progress</Badge>
                        </TableCell>
                        <TableCell>2023-03-15</TableCell>
                      </TableRow>
                    </TableBody>
                  </Table>
                </CardContent>
              </Card>
              <Card>
                <CardHeader>
                  <CardTitle>Community Feedback</CardTitle>
                  <CardDescription>See what others are saying and share your thoughts.</CardDescription>
                </CardHeader>
                <CardContent>
                  <div className="space-y-4">
                    <div className="flex items-start gap-4">
                      <Avatar>
                        <AvatarImage src="/placeholder-user.jpg" alt="User Avatar" />
                        <AvatarFallback>JD</AvatarFallback>
                      </Avatar>
                      <div className="flex-1">
                        <p className="font-medium">John Doe</p>
                        <p className="text-muted-foreground">
                          "The new dashboard is a game-changer! Really impressed with the\n improvements."
                        </p>
                      </div>
                    </div>
                    <div className="flex items-start gap-4">
                      <Avatar>
                        <AvatarImage src="/placeholder-user.jpg" alt="User Avatar" />
                        <AvatarFallback>SM</AvatarFallback>
                      </Avatar>
                      <div className="flex-1">
                        <p className="font-medium">Sarah Miller</p>
                        <p className="text-muted-foreground">
                          "I love the new mobile experience. It's so much easier to use on\n the go."
                        </p>
                      </div>
                    </div>
                    <div className="flex items-start gap-4">
                      <Avatar>
                        <AvatarImage src="/placeholder-user.jpg" alt="User Avatar" />
                        <AvatarFallback>MJ</AvatarFallback>
                      </Avatar>
                      <div className="flex-1">
                        <p className="font-medium">Michael Johnson</p>
                        <p className="text-muted-foreground">
                          "The new payment options are a game-changer. I can now use my\n preferred method."
                        </p>
                      </div>
                    </div>
                  </div>
                </CardContent>
              </Card>
            </div>
          </div>
        </section>
        <section className="py-8 sm:py-12 bg-muted">
          <div className="container grid gap-8">
            <div>
              <h2 className="text-2xl font-bold">Service Updates</h2>
              <p className="text-muted-foreground">See what we've been working on and what's coming next.</p>
            </div>
            <div className="grid gap-6 md:grid-cols-2 lg:grid-cols-3">
              <Card>
                <CardHeader>
                  <CardTitle>Recent Updates</CardTitle>
                </CardHeader>
                <CardContent>
                  <div className="space-y-4">
                    <div>
                      <p className="font-medium">Improved search functionality</p>
                      <p className="text-muted-foreground">
                        We've made it easier to find what you're looking for with our enhanced search capabilities.
                      </p>
                    </div>
                    <div>
                      <p className="font-medium">New payment options</p>
                      <p className="text-muted-foreground">
                        You can now use your preferred payment method, including PayPal and Apple Pay.
                      </p>
                    </div>
                    <div>
                      <p className="font-medium">Mobile experience enhancements</p>
                      <p className="text-muted-foreground">
                        We've optimized the mobile experience to make it easier to use on the go.
                      </p>
                    </div>
                  </div>
                </CardContent>
              </Card>
              <Card>
                <CardHeader>
                  <CardTitle>Upcoming Features</CardTitle>
                </CardHeader>
                <CardContent>
                  <div className="space-y-4">
                    <div>
                      <p className="font-medium">Personalized recommendations</p>
                      <p className="text-muted-foreground">
                        We're working on a new feature that will provide personalized product recommendations based on
                        your preferences.
                      </p>
                    </div>
                    <div>
                      <p className="font-medium">Expanded analytics</p>
                      <p className="text-muted-foreground">
                        Get more detailed insights into your business performance with our expanded analytics tools.
                      </p>
                    </div>
                    <div>
                      <p className="font-medium">Integrated collaboration</p>
                      <p className="text-muted-foreground">
                        Streamline your team's workflow with our new collaboration features, including real-time
                        document editing and task management.
                      </p>
                    </div>
                  </div>
                </CardContent>
              </Card>
              <Card>
                <CardHeader>
                  <CardTitle>Feedback Impact</CardTitle>
                </CardHeader>
                <CardContent>
                  <div className="space-y-4">
                    <div>
                      <p className="font-medium">Improved search functionality</p>
                      <p className="text-muted-foreground">
                        Based on your feedback, we've made significant improvements to our search capabilities, making
                        it easier to find what you need.
                      </p>
                    </div>
                    <div>
                      <p className="font-medium">New payment options</p>
                      <p className="text-muted-foreground">
                        You asked, and we listened! We've added new payment methods to provide more flexibility and
                        convenience.
                      </p>
                    </div>
                    <div>
                      <p className="font-medium">Mobile experience enhancements</p>
                      <p className="text-muted-foreground">
                        Your feedback on the mobile experience has helped us make significant improvements to ensure a
                        seamless on-the-go experience.
                      </p>
                    </div>
                  </div>
                </CardContent>
              </Card>
            </div>
          </div>
        </section>
      </main>
      <footer className="flex flex-col items-center justify-between gap-4 border-t bg-background px-4 py-8 sm:flex-row sm:px-6">
        <p className="text-xs text-muted-foreground">&copy; 2024 Acme Inc. All rights reserved.</p>
        <nav className="flex items-center gap-4">
          <Link href="#" className="text-xs hover:underline" prefetch={false}>
            Terms of Service
          </Link>
          <Link href="#" className="text-xs hover:underline" prefetch={false}>
            Privacy Policy
          </Link>
        </nav>
      </footer>
    </div>
  )
}

function MountainIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m8 3 4 8 5-5 5 15H2L8 3z" />
    </svg>
  )
}
